# Generated by Django 5.2 on 2025-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_referral_referralreward_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_threshold', models.PositiveIntegerField(default=3, help_text='Number of successful referrals needed for a reward.')),
                ('reward_type', models.CharField(choices=[('free_month', 'Free Month'), ('discount', 'Discount'), ('other', 'Other')], default='free_month', max_length=32)),
                ('reward_value', models.CharField(blank=True, help_text='E.g. 1 for one free month, or 10% for discount.', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
