# Generated by Django 5.1.6 on 2025-04-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_forumbadge_userforumbadge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('forum_reply', 'Forum Reply'), ('badge', 'Badge Awarded'), ('support', 'Support Update'), ('admin', 'Admin Message')], max_length=24),
        ),
    ]
