# Generated by Django 5.2 on 2025-05-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tradingmetrics_tradedetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text="Font Awesome icon class, e.g., 'fa-chart-line'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Learning Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, help_text='HTML content for articles')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'PDF Document'), ('course', 'Interactive Course'), ('webinar', 'Webinar Recording')], max_length=20)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('pro', 'Pro Plan')], default='free', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_resources/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Estimated time to complete in minutes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.learningcategory')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
